server:
  host: "127.0.0.1"
  port: "9090"

mysql:
  host: "rm-bp113u5w514cub7a6yo.mysql.rds.aliyuncs.com"
  port: "3306"
  user: "root"
  password: "Imouto949"
  database: "couple"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

kafka:
  brokers:
    - "localhost:9092"

oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com"
  access_key_id: "your_access_key_id"
  access_key_secret: "your_access_key_secret"
  bucket_name: "hupu-bucket"

jwt:
  secret: "imouto"
  expire: 86400

services:
  user:
    host: "localhost"
    port: "9001"
  post:
    host: "localhost"
    port: "8002"
  comment:
    host: "localhost"
    port: "8003"
  like:
    host: "localhost"
    port: "8004"
  follow:
    host: "localhost"
    port: "8005"
  notification:
    host: "localhost"
    port: "8006"

log:
  path: "./logs"
  level: "info"