// Code generated by Kitex v0.12.3. DO NOT EDIT.

package postservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	post "hupu/kitex_gen/post"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreatePost": kitex.NewMethodInfo(
		createPostHandler,
		newPostServiceCreatePostArgs,
		newPostServiceCreatePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPost": kitex.NewMethodInfo(
		getPostHandler,
		newPostServiceGetPostArgs,
		newPostServiceGetPostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPostList": kitex.NewMethodInfo(
		getPostListHandler,
		newPostServiceGetPostListArgs,
		newPostServiceGetPostListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	postServiceServiceInfo                = NewServiceInfo()
	postServiceServiceInfoForClient       = NewServiceInfoForClient()
	postServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return postServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return postServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return postServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PostService"
	handlerType := (*post.PostService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "post",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func createPostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceCreatePostArgs)
	realResult := result.(*post.PostServiceCreatePostResult)
	success, err := handler.(post.PostService).CreatePost(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceCreatePostArgs() interface{} {
	return post.NewPostServiceCreatePostArgs()
}

func newPostServiceCreatePostResult() interface{} {
	return post.NewPostServiceCreatePostResult()
}

func getPostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceGetPostArgs)
	realResult := result.(*post.PostServiceGetPostResult)
	success, err := handler.(post.PostService).GetPost(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceGetPostArgs() interface{} {
	return post.NewPostServiceGetPostArgs()
}

func newPostServiceGetPostResult() interface{} {
	return post.NewPostServiceGetPostResult()
}

func getPostListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*post.PostServiceGetPostListArgs)
	realResult := result.(*post.PostServiceGetPostListResult)
	success, err := handler.(post.PostService).GetPostList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPostServiceGetPostListArgs() interface{} {
	return post.NewPostServiceGetPostListArgs()
}

func newPostServiceGetPostListResult() interface{} {
	return post.NewPostServiceGetPostListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreatePost(ctx context.Context, req *post.CreatePostRequest) (r *post.CreatePostResponse, err error) {
	var _args post.PostServiceCreatePostArgs
	_args.Req = req
	var _result post.PostServiceCreatePostResult
	if err = p.c.Call(ctx, "CreatePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPost(ctx context.Context, req *post.GetPostRequest) (r *post.GetPostResponse, err error) {
	var _args post.PostServiceGetPostArgs
	_args.Req = req
	var _result post.PostServiceGetPostResult
	if err = p.c.Call(ctx, "GetPost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPostList(ctx context.Context, req *post.GetPostListRequest) (r *post.GetPostListResponse, err error) {
	var _args post.PostServiceGetPostListArgs
	_args.Req = req
	var _result post.PostServiceGetPostListResult
	if err = p.c.Call(ctx, "GetPostList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
