// Code generated by Kitex v0.12.3. DO NOT EDIT.

package notificationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	notification "hupu/kitex_gen/notification"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateNotification(ctx context.Context, req *notification.CreateNotificationRequest, callOptions ...callopt.Option) (r *notification.CreateNotificationResponse, err error)
	GetNotificationList(ctx context.Context, req *notification.GetNotificationListRequest, callOptions ...callopt.Option) (r *notification.GetNotificationListResponse, err error)
	MarkNotificationRead(ctx context.Context, req *notification.MarkNotificationReadRequest, callOptions ...callopt.Option) (r *notification.MarkNotificationReadResponse, err error)
	MarkAllNotificationsRead(ctx context.Context, req *notification.MarkAllNotificationsReadRequest, callOptions ...callopt.Option) (r *notification.MarkAllNotificationsReadResponse, err error)
	GetUnreadCount(ctx context.Context, req *notification.GetUnreadCountRequest, callOptions ...callopt.Option) (r *notification.GetUnreadCountResponse, err error)
	DeleteNotification(ctx context.Context, req *notification.DeleteNotificationRequest, callOptions ...callopt.Option) (r *notification.DeleteNotificationResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kNotificationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNotificationServiceClient struct {
	*kClient
}

func (p *kNotificationServiceClient) CreateNotification(ctx context.Context, req *notification.CreateNotificationRequest, callOptions ...callopt.Option) (r *notification.CreateNotificationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateNotification(ctx, req)
}

func (p *kNotificationServiceClient) GetNotificationList(ctx context.Context, req *notification.GetNotificationListRequest, callOptions ...callopt.Option) (r *notification.GetNotificationListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNotificationList(ctx, req)
}

func (p *kNotificationServiceClient) MarkNotificationRead(ctx context.Context, req *notification.MarkNotificationReadRequest, callOptions ...callopt.Option) (r *notification.MarkNotificationReadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkNotificationRead(ctx, req)
}

func (p *kNotificationServiceClient) MarkAllNotificationsRead(ctx context.Context, req *notification.MarkAllNotificationsReadRequest, callOptions ...callopt.Option) (r *notification.MarkAllNotificationsReadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkAllNotificationsRead(ctx, req)
}

func (p *kNotificationServiceClient) GetUnreadCount(ctx context.Context, req *notification.GetUnreadCountRequest, callOptions ...callopt.Option) (r *notification.GetUnreadCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUnreadCount(ctx, req)
}

func (p *kNotificationServiceClient) DeleteNotification(ctx context.Context, req *notification.DeleteNotificationRequest, callOptions ...callopt.Option) (r *notification.DeleteNotificationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteNotification(ctx, req)
}
