// Code generated by Kitex v0.12.3. DO NOT EDIT.

package notificationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	notification "hupu/kitex_gen/notification"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateNotification": kitex.NewMethodInfo(
		createNotificationHandler,
		newNotificationServiceCreateNotificationArgs,
		newNotificationServiceCreateNotificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetNotificationList": kitex.NewMethodInfo(
		getNotificationListHandler,
		newNotificationServiceGetNotificationListArgs,
		newNotificationServiceGetNotificationListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkNotificationRead": kitex.NewMethodInfo(
		markNotificationReadHandler,
		newNotificationServiceMarkNotificationReadArgs,
		newNotificationServiceMarkNotificationReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkAllNotificationsRead": kitex.NewMethodInfo(
		markAllNotificationsReadHandler,
		newNotificationServiceMarkAllNotificationsReadArgs,
		newNotificationServiceMarkAllNotificationsReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUnreadCount": kitex.NewMethodInfo(
		getUnreadCountHandler,
		newNotificationServiceGetUnreadCountArgs,
		newNotificationServiceGetUnreadCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteNotification": kitex.NewMethodInfo(
		deleteNotificationHandler,
		newNotificationServiceDeleteNotificationArgs,
		newNotificationServiceDeleteNotificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	notificationServiceServiceInfo                = NewServiceInfo()
	notificationServiceServiceInfoForClient       = NewServiceInfoForClient()
	notificationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return notificationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return notificationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return notificationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "NotificationService"
	handlerType := (*notification.NotificationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "notification",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func createNotificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notification.NotificationServiceCreateNotificationArgs)
	realResult := result.(*notification.NotificationServiceCreateNotificationResult)
	success, err := handler.(notification.NotificationService).CreateNotification(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceCreateNotificationArgs() interface{} {
	return notification.NewNotificationServiceCreateNotificationArgs()
}

func newNotificationServiceCreateNotificationResult() interface{} {
	return notification.NewNotificationServiceCreateNotificationResult()
}

func getNotificationListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notification.NotificationServiceGetNotificationListArgs)
	realResult := result.(*notification.NotificationServiceGetNotificationListResult)
	success, err := handler.(notification.NotificationService).GetNotificationList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceGetNotificationListArgs() interface{} {
	return notification.NewNotificationServiceGetNotificationListArgs()
}

func newNotificationServiceGetNotificationListResult() interface{} {
	return notification.NewNotificationServiceGetNotificationListResult()
}

func markNotificationReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notification.NotificationServiceMarkNotificationReadArgs)
	realResult := result.(*notification.NotificationServiceMarkNotificationReadResult)
	success, err := handler.(notification.NotificationService).MarkNotificationRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceMarkNotificationReadArgs() interface{} {
	return notification.NewNotificationServiceMarkNotificationReadArgs()
}

func newNotificationServiceMarkNotificationReadResult() interface{} {
	return notification.NewNotificationServiceMarkNotificationReadResult()
}

func markAllNotificationsReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notification.NotificationServiceMarkAllNotificationsReadArgs)
	realResult := result.(*notification.NotificationServiceMarkAllNotificationsReadResult)
	success, err := handler.(notification.NotificationService).MarkAllNotificationsRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceMarkAllNotificationsReadArgs() interface{} {
	return notification.NewNotificationServiceMarkAllNotificationsReadArgs()
}

func newNotificationServiceMarkAllNotificationsReadResult() interface{} {
	return notification.NewNotificationServiceMarkAllNotificationsReadResult()
}

func getUnreadCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notification.NotificationServiceGetUnreadCountArgs)
	realResult := result.(*notification.NotificationServiceGetUnreadCountResult)
	success, err := handler.(notification.NotificationService).GetUnreadCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceGetUnreadCountArgs() interface{} {
	return notification.NewNotificationServiceGetUnreadCountArgs()
}

func newNotificationServiceGetUnreadCountResult() interface{} {
	return notification.NewNotificationServiceGetUnreadCountResult()
}

func deleteNotificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notification.NotificationServiceDeleteNotificationArgs)
	realResult := result.(*notification.NotificationServiceDeleteNotificationResult)
	success, err := handler.(notification.NotificationService).DeleteNotification(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceDeleteNotificationArgs() interface{} {
	return notification.NewNotificationServiceDeleteNotificationArgs()
}

func newNotificationServiceDeleteNotificationResult() interface{} {
	return notification.NewNotificationServiceDeleteNotificationResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateNotification(ctx context.Context, req *notification.CreateNotificationRequest) (r *notification.CreateNotificationResponse, err error) {
	var _args notification.NotificationServiceCreateNotificationArgs
	_args.Req = req
	var _result notification.NotificationServiceCreateNotificationResult
	if err = p.c.Call(ctx, "CreateNotification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetNotificationList(ctx context.Context, req *notification.GetNotificationListRequest) (r *notification.GetNotificationListResponse, err error) {
	var _args notification.NotificationServiceGetNotificationListArgs
	_args.Req = req
	var _result notification.NotificationServiceGetNotificationListResult
	if err = p.c.Call(ctx, "GetNotificationList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkNotificationRead(ctx context.Context, req *notification.MarkNotificationReadRequest) (r *notification.MarkNotificationReadResponse, err error) {
	var _args notification.NotificationServiceMarkNotificationReadArgs
	_args.Req = req
	var _result notification.NotificationServiceMarkNotificationReadResult
	if err = p.c.Call(ctx, "MarkNotificationRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkAllNotificationsRead(ctx context.Context, req *notification.MarkAllNotificationsReadRequest) (r *notification.MarkAllNotificationsReadResponse, err error) {
	var _args notification.NotificationServiceMarkAllNotificationsReadArgs
	_args.Req = req
	var _result notification.NotificationServiceMarkAllNotificationsReadResult
	if err = p.c.Call(ctx, "MarkAllNotificationsRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUnreadCount(ctx context.Context, req *notification.GetUnreadCountRequest) (r *notification.GetUnreadCountResponse, err error) {
	var _args notification.NotificationServiceGetUnreadCountArgs
	_args.Req = req
	var _result notification.NotificationServiceGetUnreadCountResult
	if err = p.c.Call(ctx, "GetUnreadCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteNotification(ctx context.Context, req *notification.DeleteNotificationRequest) (r *notification.DeleteNotificationResponse, err error) {
	var _args notification.NotificationServiceDeleteNotificationArgs
	_args.Req = req
	var _result notification.NotificationServiceDeleteNotificationResult
	if err = p.c.Call(ctx, "DeleteNotification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
