// Code generated by Kitex v0.12.3. DO NOT EDIT.
package notificationservice

import (
	server "github.com/cloudwego/kitex/server"
	notification "hupu/kitex_gen/notification"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler notification.NotificationService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler notification.NotificationService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
