// Code generated by Kitex v0.12.3. DO NOT EDIT.

package likeservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	like "hupu/kitex_gen/like"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Like(ctx context.Context, req *like.LikeRequest, callOptions ...callopt.Option) (r *like.LikeResponse, err error)
	Unlike(ctx context.Context, req *like.UnlikeRequest, callOptions ...callopt.Option) (r *like.UnlikeResponse, err error)
	IsLiked(ctx context.Context, req *like.LikeRequest, callOptions ...callopt.Option) (r *like.LikeResponse, err error)
	GetLikeList(ctx context.Context, req *like.GetLikeListRequest, callOptions ...callopt.Option) (r *like.GetLikeListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kLikeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLikeServiceClient struct {
	*kClient
}

func (p *kLikeServiceClient) Like(ctx context.Context, req *like.LikeRequest, callOptions ...callopt.Option) (r *like.LikeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Like(ctx, req)
}

func (p *kLikeServiceClient) Unlike(ctx context.Context, req *like.UnlikeRequest, callOptions ...callopt.Option) (r *like.UnlikeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Unlike(ctx, req)
}

func (p *kLikeServiceClient) IsLiked(ctx context.Context, req *like.LikeRequest, callOptions ...callopt.Option) (r *like.LikeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IsLiked(ctx, req)
}

func (p *kLikeServiceClient) GetLikeList(ctx context.Context, req *like.GetLikeListRequest, callOptions ...callopt.Option) (r *like.GetLikeListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLikeList(ctx, req)
}
