@host = http://127.0.0.1:8080

POST {{host}}/api/v1/user/register
Content-Type: application/json

{
  "username": "testuser4",
  "password": "123456",
  "phone": "150234216654",
  "code": "1234"
}




POST {{host}}/api/v1/user/login
Content-Type: application/json

{
  "username": "testuser4",
  "password": "123456"
}
