version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hupu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hupu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hupu-network

  redis:
    image: redis:7-alpine
    container_name: hupu-redis
    ports:
      - "6379:6379"
    networks:
      - hupu-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: hupu-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - hupu-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: hupu-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - hupu-network

  user-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user
    container_name: hupu-user-service
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      - redis
    networks:
      - hupu-network

  post-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.post
    container_name: hupu-post-service
    ports:
      - "8002:8002"
    depends_on:
      - mysql
      - redis
    networks:
      - hupu-network

  comment-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.comment
    container_name: hupu-comment-service
    ports:
      - "8003:8003"
    depends_on:
      - mysql
      - redis
    networks:
      - hupu-network

  like-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.like
    container_name: hupu-like-service
    ports:
      - "8004:8004"
    depends_on:
      - mysql
      - redis
    networks:
      - hupu-network

  follow-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.follow
    container_name: hupu-follow-service
    ports:
      - "8005:8005"
    depends_on:
      - mysql
      - redis
    networks:
      - hupu-network

  notification-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.notification
    container_name: hupu-notification-service
    ports:
      - "8006:8006"
    depends_on:
      - mysql
      - redis
    networks:
      - hupu-network

  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gateway
    container_name: hupu-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - post-service
      - comment-service
      - like-service
      - follow-service
      - notification-service
    networks:
      - hupu-network

volumes:
  mysql_data:

networks:
  hupu-network:
    driver: bridge