// Code generated by Kitex v0.12.3. DO NOT EDIT.

package commentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	comment "hupu/kitex_gen/comment"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateComment(ctx context.Context, req *comment.CreateCommentRequest, callOptions ...callopt.Option) (r *comment.CreateCommentResponse, err error)
	GetCommentList(ctx context.Context, req *comment.GetCommentListRequest, callOptions ...callopt.Option) (r *comment.GetCommentListResponse, err error)
	GetComment(ctx context.Context, req *comment.GetCommentRequest, callOptions ...callopt.Option) (r *comment.GetCommentResponse, err error)
	GetUserComments(ctx context.Context, req *comment.GetUserCommentsRequest, callOptions ...callopt.Option) (r *comment.GetUserCommentsResponse, err error)
	DeleteComment(ctx context.Context, req *comment.DeleteCommentRequest, callOptions ...callopt.Option) (r *comment.DeleteCommentResponse, err error)
	RateComment(ctx context.Context, req *comment.RateCommentRequest, callOptions ...callopt.Option) (r *comment.RateCommentResponse, err error)
	GetUserCommentRating(ctx context.Context, req *comment.GetUserCommentRatingRequest, callOptions ...callopt.Option) (r *comment.GetUserCommentRatingResponse, err error)
	UpdateCommentRating(ctx context.Context, req *comment.UpdateCommentRatingRequest, callOptions ...callopt.Option) (r *comment.UpdateCommentRatingResponse, err error)
	DeleteCommentRating(ctx context.Context, req *comment.DeleteCommentRatingRequest, callOptions ...callopt.Option) (r *comment.DeleteCommentRatingResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) CreateComment(ctx context.Context, req *comment.CreateCommentRequest, callOptions ...callopt.Option) (r *comment.CreateCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateComment(ctx, req)
}

func (p *kCommentServiceClient) GetCommentList(ctx context.Context, req *comment.GetCommentListRequest, callOptions ...callopt.Option) (r *comment.GetCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, req)
}

func (p *kCommentServiceClient) GetComment(ctx context.Context, req *comment.GetCommentRequest, callOptions ...callopt.Option) (r *comment.GetCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetComment(ctx, req)
}

func (p *kCommentServiceClient) GetUserComments(ctx context.Context, req *comment.GetUserCommentsRequest, callOptions ...callopt.Option) (r *comment.GetUserCommentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserComments(ctx, req)
}

func (p *kCommentServiceClient) DeleteComment(ctx context.Context, req *comment.DeleteCommentRequest, callOptions ...callopt.Option) (r *comment.DeleteCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}

func (p *kCommentServiceClient) RateComment(ctx context.Context, req *comment.RateCommentRequest, callOptions ...callopt.Option) (r *comment.RateCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RateComment(ctx, req)
}

func (p *kCommentServiceClient) GetUserCommentRating(ctx context.Context, req *comment.GetUserCommentRatingRequest, callOptions ...callopt.Option) (r *comment.GetUserCommentRatingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserCommentRating(ctx, req)
}

func (p *kCommentServiceClient) UpdateCommentRating(ctx context.Context, req *comment.UpdateCommentRatingRequest, callOptions ...callopt.Option) (r *comment.UpdateCommentRatingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCommentRating(ctx, req)
}

func (p *kCommentServiceClient) DeleteCommentRating(ctx context.Context, req *comment.DeleteCommentRatingRequest, callOptions ...callopt.Option) (r *comment.DeleteCommentRatingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCommentRating(ctx, req)
}
